import electron from 'electron';
const { app, BrowserWindow, ipcMain } = electron;
import path from 'node:path'; import fs from 'node:fs'; import Database from './db.js';
import { fileURLToPath } from 'node:url'; import { ensureContent } from './content.js'; import { userMigrations } from './migrations.js'; import { levelFromXp, shuffled, streak, medalFor } from './domain.js';
import { readChapter } from './bible.js';
import electronUpdater from 'electron-updater';
const { autoUpdater } = electronUpdater;
const here=path.dirname(fileURLToPath(import.meta.url)); let user:Database, content:Database; let activeProfileId:number|null=null; let lastInteraction=Date.now(), accrued=0;
const isoDay=()=>new Date().toLocaleDateString('en-CA'); const now=()=>new Date().toISOString();
function configureAutoUpdates(win:InstanceType<typeof BrowserWindow>){
 if(!app.isPackaged)return;
 autoUpdater.autoDownload=true;
 autoUpdater.autoInstallOnAppQuit=true;
 autoUpdater.on('update-downloaded',async info=>{
  const result=await electron.dialog.showMessageBox(win,{type:'info',title:'Update ready',message:`Bible Questions App ${info.version} is ready.`,detail:'Restart now to install it. Your profiles and progress will be preserved.',buttons:['Restart and update','Later'],defaultId:0,cancelId:1});
  if(result.response===0)autoUpdater.quitAndInstall(false,true);
 });
 autoUpdater.on('error',error=>console.error('Automatic update error:',error));
 setTimeout(()=>void autoUpdater.checkForUpdatesAndNotify(),10000);
 setInterval(()=>void autoUpdater.checkForUpdatesAndNotify(),6*60*60*1000);
}
function registerBibleSearch(){
 ipcMain.handle('bible:search',(_,value)=>{
  const query=String(value??'').trim();
  if(query.length<2)return [];
  return content.prepare('SELECT v.book_id bookId,b.name bookName,v.chapter,v.verse,v.text FROM verses v JOIN books b ON b.id=v.book_id WHERE v.text LIKE ? ORDER BY b.book_order,v.chapter,v.verse LIMIT 100').all(`%${query}%`);
 });
}
function registerAnnotations(){
 ipcMain.handle('note:set',(_,p)=>{if(!activeProfileId)throw new Error('No profile');const note=String(p.note??'').trim();if(note)user.prepare('INSERT INTO verse_notes VALUES(?,?,?,?,?,?) ON CONFLICT(profile_id,book_id,chapter,verse) DO UPDATE SET note=excluded.note,updated_at=excluded.updated_at').run(activeProfileId,p.bookId,p.chapter,p.verse,note,now());else user.prepare('DELETE FROM verse_notes WHERE profile_id=? AND book_id=? AND chapter=? AND verse=?').run(activeProfileId,p.bookId,p.chapter,p.verse);});
 ipcMain.handle('bookmark:toggle',(_,p)=>{if(!activeProfileId)throw new Error('No profile');const exists=user.prepare('SELECT 1 FROM bookmarks WHERE profile_id=? AND book_id=? AND chapter=? AND verse=?').get(activeProfileId,p.bookId,p.chapter,p.verse);if(exists)user.prepare('DELETE FROM bookmarks WHERE profile_id=? AND book_id=? AND chapter=? AND verse=?').run(activeProfileId,p.bookId,p.chapter,p.verse);else user.prepare('INSERT INTO bookmarks VALUES(?,?,?,?,?)').run(activeProfileId,p.bookId,p.chapter,p.verse,now());});
}
function migrate(db:Database){db.exec('CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)'); const applied=new Set((db.prepare('SELECT version FROM schema_migrations').all() as unknown as {version:number}[]).map(x=>x.version)); userMigrations.forEach((sql,i)=>{if(!applied.has(i+1))db.transaction(()=>{db.exec(sql);db.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(i+1,now())})();});}
function profile(id:number){return user.prepare('SELECT id,name,avatar_id avatarId,xp,current_streak currentStreak,longest_streak longestStreak,last_active_date lastActiveDate,selected_banner selectedBanner FROM profiles WHERE id=?').get(id);}
function touch(id:number){const p:any=profile(id), s=streak(p.lastActiveDate,p.currentStreak,p.longestStreak,isoDay()); user.prepare('UPDATE profiles SET current_streak=?,longest_streak=?,last_active_date=? WHERE id=?').run(s.current,s.longest,isoDay(),id);}
function bootstrap(){const profiles=user.prepare('SELECT id,name,avatar_id avatarId,xp,current_streak currentStreak,longest_streak longestStreak,last_active_date lastActiveDate,selected_banner selectedBanner FROM profiles ORDER BY id').all(); if(activeProfileId&&!profiles.some((p:any)=>p.id===activeProfileId))activeProfileId=null; const books=content.prepare('SELECT id,name,testament,book_order `order`,chapters FROM books ORDER BY book_order').all(); const animals=content.prepare('SELECT id,name,emoji,unlock_level unlockLevel FROM animals ORDER BY sort_order').all(); return {profiles,activeProfile:activeProfileId?profile(activeProfileId):null,books,animals,appVersion:app.getVersion(),bankVersion:(content.prepare("SELECT value FROM metadata WHERE key='question_bank_version'").get() as any).value};}
function currentSession(id:number){const s:any=user.prepare("SELECT * FROM sessions WHERE profile_id=? AND status='active' ORDER BY id DESC LIMIT 1").get(id); return s?sessionState(s):null;}
function sessionState(s:any){const order:string[]=JSON.parse(s.question_order), choices:number[][]=JSON.parse(s.choice_orders), qid=order[s.current_index]; const raw:any=qid?content.prepare('SELECT q.*,b.name book_name FROM questions q JOIN books b ON b.id=q.book_id WHERE q.id=?').get(qid):null; const ans:any=raw?user.prepare('SELECT * FROM session_answers WHERE session_id=? AND question_id=?').get(s.id,qid):null; const totals:any=user.prepare('SELECT COUNT(*) answered,COALESCE(SUM(is_correct),0) correct FROM session_answers WHERE session_id=?').get(s.id); let current=null,correctIndex=null;if(raw){const vals=[raw.answer_a,raw.answer_b,raw.answer_c,raw.answer_d], map=choices[s.current_index];current={id:raw.id,bookId:raw.book_id,bookName:raw.book_name,chapter:raw.chapter,verseStart:raw.verse_start,verseEnd:raw.verse_end,text:raw.question_text,choices:map.map(i=>vals[i])};correctIndex=map.indexOf(raw.correct_index);} return {sessionId:s.id,mode:s.mode,bookId:s.book_id,title:s.title,currentIndex:s.current_index,total:order.length,answered:totals.answered,correct:totals.correct,completed:s.status==='completed',current,selectedIndex:ans?.selected_choice??null,correctIndex:ans?correctIndex:null,isCorrect:ans?!!ans.is_correct:null};}
function createSession(profileId:number,mode:string,bookId:string='',chapterStart:number=1,chapterEnd:number=chapterStart){let rows:any[]; if(mode==='daily'){const date=isoDay();let d:any=user.prepare('SELECT question_id FROM daily_questions WHERE profile_id=? AND local_date=?').get(profileId,date);if(!d){const all=content.prepare('SELECT id FROM questions').all() as any[]; const picked=all[Math.abs([...date].reduce((a,c)=>a+c.charCodeAt(0),profileId))%all.length];user.prepare('INSERT INTO daily_questions(profile_id,local_date,question_id) VALUES(?,?,?)').run(profileId,date,picked.id);d={question_id:picked.id};}rows=[{id:d.question_id}];}else {rows=content.prepare(`SELECT id FROM questions WHERE book_id=? ${mode==='practice'?'AND chapter BETWEEN ? AND ?':''}`).all(...(mode==='practice'?[bookId,chapterStart,chapterEnd]:[bookId])) as any[];} if(!rows.length)throw new Error('No questions are available for this selection yet.'); const ids=shuffled(rows.map(x=>x.id));const maps=ids.map(()=>shuffled([0,1,2,3]));const name=(content.prepare('SELECT name FROM books WHERE id=?').get(bookId) as any)?.name;const title=mode==='daily'?"Today's Question":mode==='full'?`${name} — Full Quiz`:`${name} ${chapterStart===chapterEnd?'Chapter '+chapterStart:`Chapters ${chapterStart}–${chapterEnd}`}`;const info=user.prepare('INSERT INTO sessions(profile_id,mode,book_id,chapter_start,chapter_end,title,question_order,choice_orders,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(profileId,mode,bookId||null,chapterStart,chapterEnd,title,JSON.stringify(ids),JSON.stringify(maps),now());return sessionState(user.prepare('SELECT * FROM sessions WHERE id=?').get(info.lastInsertRowid));}
function handlers(){ipcMain.handle('bootstrap',()=>bootstrap());ipcMain.handle('profile:create',(_,p)=>{const info=user.prepare('INSERT INTO profiles(name,avatar_id,created_at) VALUES(?,?,?)').run(String(p.name).trim().slice(0,40),p.avatarId,now());activeProfileId=Number(info.lastInsertRowid);touch(activeProfileId);return bootstrap();});ipcMain.handle('profile:select',(_,id)=>{activeProfileId=Number(id);touch(activeProfileId);return bootstrap();});ipcMain.handle('profile:current',()=>activeProfileId?profile(activeProfileId):null);ipcMain.handle('profile:avatar',(_,avatarId)=>{if(!activeProfileId)throw new Error('No profile');const animal:any=content.prepare('SELECT id,unlock_level FROM animals WHERE id=?').get(String(avatarId));if(!animal)throw new Error('Avatar not found.');const current:any=profile(activeProfileId);if(levelFromXp(current.xp).level<animal.unlock_level)throw new Error(`This avatar unlocks at level ${animal.unlock_level}.`);user.prepare('UPDATE profiles SET avatar_id=? WHERE id=?').run(animal.id,activeProfileId);return bootstrap();});
 ipcMain.handle('session:active',()=>activeProfileId?currentSession(activeProfileId):null);ipcMain.handle('session:start',(_,p)=>{if(!activeProfileId)throw new Error('Select a profile first.');return createSession(activeProfileId,p.mode,p.bookId,p.chapterStart,p.chapterEnd);});ipcMain.handle('session:answer',(_,p)=>{if(!activeProfileId)throw new Error('No profile');const s:any=user.prepare('SELECT * FROM sessions WHERE id=? AND profile_id=?').get(p.sessionId,activeProfileId);const state:any=sessionState(s);if(state.selectedIndex!==null)return state;const raw:any=content.prepare('SELECT correct_index FROM questions WHERE id=?').get(state.current.id);const maps=JSON.parse(s.choice_orders);const correct=maps[s.current_index].indexOf(raw.correct_index);const ok=p.selectedIndex===correct;
  // A daily question may be reopened, but its question XP is awarded only once.
  const priorDaily:any=s.mode==='daily'?user.prepare('SELECT answered_at FROM daily_questions WHERE profile_id=? AND local_date=?').get(activeProfileId,isoDay()):null;
  user.transaction(()=>{user.prepare('INSERT INTO session_answers VALUES(?,?,?,?,?,?)').run(s.id,state.current.id,p.selectedIndex,correct,ok?1:0,now());if(!priorDaily?.answered_at)user.prepare('UPDATE profiles SET xp=xp+? WHERE id=?').run(ok?2:1,activeProfileId);if(s.mode==='daily'&&!priorDaily?.answered_at)user.prepare('UPDATE daily_questions SET selected_choice=?,correct_choice=?,is_correct=?,answered_at=? WHERE profile_id=? AND local_date=?').run(p.selectedIndex,correct,ok?1:0,now(),activeProfileId,isoDay());})();return sessionState(s);});
 ipcMain.handle('session:next',(_,id)=>{const s:any=user.prepare('SELECT * FROM sessions WHERE id=?').get(id);const st:any=sessionState(s);if(st.selectedIndex===null)throw new Error('Answer before continuing.');if(s.current_index+1>=st.total){user.transaction(()=>{user.prepare("UPDATE sessions SET status='completed',completed_at=? WHERE id=?").run(now(),id);if(s.mode==='full'){const pct=st.total?st.correct/st.total*100:0;user.prepare('INSERT INTO book_stats(profile_id,book_id,attempts,best_percent,last_question_count) VALUES(?,?,1,?,?) ON CONFLICT(profile_id,book_id) DO UPDATE SET attempts=attempts+1,best_percent=MAX(best_percent,excluded.best_percent),last_question_count=excluded.last_question_count').run(s.profile_id,s.book_id,pct,st.total);}})();return {...sessionState({...s,status:'completed'}),completed:true};}user.prepare('UPDATE sessions SET current_index=current_index+1 WHERE id=?').run(id);return sessionState(user.prepare('SELECT * FROM sessions WHERE id=?').get(id));});
 ipcMain.handle('bible:chapter',(_,p)=>{if(!activeProfileId)throw new Error('No profile');user.prepare('INSERT INTO reading_positions VALUES(?,?,?,?) ON CONFLICT(profile_id) DO UPDATE SET book_id=excluded.book_id,chapter=excluded.chapter,updated_at=excluded.updated_at').run(activeProfileId,p.bookId,p.chapter,now());return readChapter(content,user,activeProfileId,p.bookId,p.chapter);});ipcMain.handle('highlight:set',(_,p)=>{if(!activeProfileId)throw new Error('No profile');if(p.color)user.prepare('INSERT INTO highlights VALUES(?,?,?,?,?,?) ON CONFLICT(profile_id,book_id,chapter,verse) DO UPDATE SET color=excluded.color,updated_at=excluded.updated_at').run(activeProfileId,p.bookId,p.chapter,p.verse,p.color,now());else user.prepare('DELETE FROM highlights WHERE profile_id=? AND book_id=? AND chapter=? AND verse=?').run(activeProfileId,p.bookId,p.chapter,p.verse);});
 ipcMain.handle('stats',()=>{if(!activeProfileId)return null;const books=(user.prepare('SELECT * FROM book_stats WHERE profile_id=?').all(activeProfileId) as any[]).map(book=>{const current=(content.prepare('SELECT COUNT(*) count FROM questions WHERE book_id=?').get(book.book_id) as {count:number}).count;const latest:any=book.last_question_count===null?user.prepare("SELECT question_order FROM sessions WHERE profile_id=? AND book_id=? AND mode='full' AND status='completed' ORDER BY completed_at DESC LIMIT 1").get(activeProfileId,book.book_id):null;const previous=book.last_question_count??(latest?JSON.parse(latest.question_order).length:null);return {...book,new_questions:previous===null?0:Math.max(0,current-previous)}});const full:any=user.prepare("SELECT COUNT(DISTINCT s.id) completed,COUNT(a.question_id) answered,COALESCE(SUM(a.is_correct),0) correct FROM sessions s LEFT JOIN session_answers a ON a.session_id=s.id WHERE s.profile_id=? AND s.mode='full' AND s.status='completed'").get(activeProfileId);const daily:any=user.prepare('SELECT COUNT(*) answered,COALESCE(SUM(is_correct),0) correct FROM daily_questions WHERE profile_id=? AND answered_at IS NOT NULL').get(activeProfileId);return {books,full,daily};});
 ipcMain.on('activity',()=>lastInteraction=Date.now());}
app.whenReady().then(()=>{const data=app.getPath('userData');fs.mkdirSync(data,{recursive:true});user=new Database(path.join(data,'selah-user.sqlite'));user.pragma('foreign_keys=ON');user.pragma('journal_mode=WAL');migrate(user);content=ensureContent(path.join(data,'selah-content.sqlite'),path.join(app.isPackaged?process.resourcesPath:process.cwd(),'content','engwebp_vpl.txt'));handlers();registerBibleSearch();registerAnnotations();setInterval(()=>{if(activeProfileId&&Date.now()-lastInteraction<300000){accrued+=5;if(accrued>=60){user.prepare('UPDATE profiles SET xp=xp+0.08,active_seconds=active_seconds+60 WHERE id=?').run(activeProfileId);accrued-=60;}}},5000);const win=new BrowserWindow({width:1280,height:820,minWidth:900,minHeight:650,title:'Bible Questions App',backgroundColor:'#f5f0e6',webPreferences:{preload:path.join(app.getAppPath(),'electron','preload.cjs'),contextIsolation:true,nodeIntegration:false}});configureAutoUpdates(win);if(process.env.VITE_DEV_SERVER_URL)win.loadURL(process.env.VITE_DEV_SERVER_URL);else win.loadFile(path.join(app.getAppPath(),'dist','index.html'));});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
